networks:
  bridgenetwork: #define bridge network that connects containers together internally
    driver: bridge

services:
  front-end: #web application front-end
    build: #build docker image using Dockerfile in front-end directory
      context: ./front-end
      target: production
    environment: #set NODE_ENV environment variable
      NODE_ENV: production
    networks: #connect service to bridgenetwork
      - bridgenetwork
    ports: #map host port 3000 and 24678 to port 3000 and 24678 of webapp front end service
      - 3000:3000
      - 24678:24678
    depends_on: #starts service after chat-module
      - chat-module
    profiles:
      - production

  front-end-dev: #web application front-end for development
    build: #build docker image using Dockerfile in front-end directory
      context: ./front-end
      target: development
    environment: #set NODE_ENV environment variable
      NODE_ENV: development
    volumes:
      - ./front-end:/app
      - /app/remix-app/node_modules
    networks: #connect service to bridgenetwork
      - bridgenetwork
    ports: #map host port 3000 and 24678 to port 3000 and 24678 of webapp front end service
      - 3000:3000
      - 24678:24678
    depends_on: #starts service after chat-module
      - chat-module
    profiles:
      - development

  chat-module: #chat-module
    build: #build docker image using Dockerfile in chat-module directory
      context: ./AI_modules/chat-module
    networks: #connect service to bridgenetwork
      - bridgenetwork
    ports: #map host port 8001 to port 8001 of chat-module service
      - 8001:8001
    depends_on: #starts service after retrieval-module
      - retrieval-module
    environment:
      - MODEL_NAME=${MODEL_NAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  retrieval-module: #retrieval-module
    build: #build docker image using Dockerfile in retrieval-module directory
      context: ./AI_modules/retrieval-module
    networks: #connect service to bridgenetwork
      - bridgenetwork
    ports: #map host port 8002 to port 8002 of retrieval-module service
      - 8000:8000
    depends_on: #starts service after db
      - data-module
    volumes: #create volume "/retrieval-data" in container that is mapped to "/retrieval-data" in local directory of host machine that persists data
      - ./retrieval-data:/retrieval-data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  data-module: #data-module
    build: #build docker image using Dockerfile in data-module directory
      context: ./data-module
    networks: #connect service to bridgenetwork
      - bridgenetwork
    ports: #map host port 8003 to port 8003 of data-module service
      - 8003:8003
    depends_on: #starts service after db
      db:
        condition: service_healthy

  db: #database
    image: pgvector/pgvector:pg17
    networks:
      - bridgenetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: